# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=line-too-long
# pylint: disable=too-many-lines

from knack.help_files import helps  # pylint: disable=unused-import

helps['copilot'] = """
type: command
short-summary: az copilot your CLI AI assistant
long-summary: |-
    az copilot opens a sidebar and wakes up your CLI AI assistant.
    You can Get the Azure CLI commands or scripts for management operations of Azure resources.
    Even end-to-end scenario scripts involving multiple different Azure resources.
examples:
  - name: Sample questions
    text: |
        - Give me a CLI script to create a VM with a public IP address
        - How to use Azure CLI script to backup an Azure SQL single database to an Azure storage container
        - How to connect an App Service app to an Azure Cache for Redis using Azure CLI
        - What is the CLI command to start a SAP system using Azure Center for SAP solutions?
"""

helps['copilot'] = """
type: command
short-summary: az copilot your CLI AI assistant
long-summary: |-
    az copilot opens a sidebar and wakes up your CLI AI assistant.
    You can Get the Azure CLI commands or scripts for management operations of Azure resources.
    Even end-to-end scenario scripts involving multiple different Azure resources.
examples:
  - name: Sample questions
    text: |
        - Give me a CLI script to create a VM with a public IP address
        - How to use Azure CLI script to backup an Azure SQL single database to an Azure storage container
        - How to connect an App Service app to an Azure Cache for Redis using Azure CLI
        - What is the CLI command to start a SAP system using Azure Center for SAP solutions?
"""